### ISSUE TITLE
Scrollbar Small Issue

### ISSUE THREAD

**Issue by ILoveNox** [Izheil/Dark-userstyles#3]
Cheers Guys,
First, kudos on the amazing theme and effort.
Now my "small" issue is this:
With your theme, I'm also using the custom scrollbars colors you made on userstyles.org. 
The scrollbars (of the web pages) have the up/down (left/right) arrows in bright white while if I use the new dynamic dark scrollbar of Firefox (the one that changes color if you are on a website with dark background) the arrows are in gray color which I prefer. How can I make those arrows in your scrollbar to be gray too not white.
Thanks in advance.
Cheers.
![Screenshot (3)](https://user-images.githubusercontent.com/68702893/88311739-9370c200-cd11-11ea-915c-4889e59b78ef.png)
![Screenshot (4)](https://user-images.githubusercontent.com/68702893/88311741-94095880-cd11-11ea-855a-06df9ac4c3e3.png)

**Comment by ILoveNox** [comment]
@Izheil  Thanks a lot for your reply. Never thought I'd get a reply this fast :)
Followed your advice (from inside stylus) and it worked. Thanks a lot !
Cheers.

**Comment by ILoveNox** [comment]
@Izheil Sorry mate to bother you again...but on light themed pages the scroll bar is almost gray again (I guess its transparency shows the webpage beneath it)...will play with the Alpha channel and see.
![Screenshot (5)](https://user-images.githubusercontent.com/68702893/88316843-b2268700-cd18-11ea-9aab-0a24ed9c9ec6.png)

**Comment by Izheil** [comment]
Yeah.... sadly Firefox doesn't allow direct customization to those arrows through regular CSS, so I can't do much about it.
The only possible way would be patching firefox with JS to allow elevated CSS, but... that seems a bit overkill for those buttons.

The only other workaround is using a dark theme on your OS, which would turn the scrollbar dark everywhere, and make the scrollbar stop adapting to pages as well.

**Comment by ILoveNox** [comment]
@Izheil You're right it'd be too much to use JS for such a small issue.
I already have dark theme enabled (Win10) but it doesn't affect the scrollbars in Firefox (I have enabled ui.systemUsesDarkTheme  in about:config).
Anyway I am sorry to have bothered you for such an issue and thank you again for being this helpful.
Cheers.

**Comment by Izheil** [comment]
Don't worry about it, that's what the issues section is for after all!
Sorry that I couldn't help more.

Still... if you have dark theme enabled on Windows it should keep scrollbars dark all the time. 
You could disable the per-site adjust changing these on `about:config`:
`layout.css.scrollbar-color.enabled` -> This one doesn't seem to exist on nightly but does on stable.
`widget.disable-dark-scrollbar` -> Might look ironic, but for me at least it keeps the dark scrollbar dark.

Although if it's not registering the dark theme for some reason, I'm not sure those would help.

**Comment by ILoveNox** [comment]
Will try and let you know. I have the first one set to true and the second to false, right?

**Comment by Izheil** [comment]
`layout.css.scrollbar-color.enabled` should be false, and `widget.disable-dark-scrollbar` should be true suposedly.

**Comment by ILoveNox** [comment]
@Izheil Well I guess there is no hope for now....all combinations don't work....Thanks anyway man.
Cheers.
