### ISSUE TITLE
Minor issue with firefox scrollbar styling

### ISSUE THREAD

**Issue by namakeingo** [Izheil/Dark-userstyles#4]
Hi,
The style is overall good and working. However, there is a small issue with the firefox part.
You need to set the property scrollbar-width as global. Otherwhise, the thickness will be adjusted for the main scrollbar, but not for any other scrollbar inside the page.
![Capture](https://user-images.githubusercontent.com/22453858/94768678-f6cd3f00-03a7-11eb-9401-65b862856d96.PNG)

**Comment by Izheil** [comment]
Thank you for the heads up!
I had it like that on the [Firefox theme userContent.css](https://github.com/Izheil/Quantum-Nox-Firefox-Dark-Full-Theme/blob/a4ecaee6ea566b5654f8d46b14442b5a406b5c9a/Full%20dark%20theme/userContent.css#L143), but looks like I forgot to add it to the userstyle.
It should be fixed now.

**Comment by namakeingo** [comment]
You are welcome. And also thank you for the quick update, it is fine now
