### ISSUE TITLE
Multirow

### ISSUE THREAD

**Issue by felitsyn** [Izheil/Dark-userstyles#5]
Izheil, sorry I'm writing here, but the Multirow archive is closed.

"Multirow" has stopped working correctly in Firefox Developer Edition. It happened a few days ago. The picture shows that the current tab is hanging in the air, only the first row is visible.
![multirow](https://user-images.githubusercontent.com/9796044/202983114-8f2fe324-4d6a-45c4-b699-1c09186cea8a.png)

**Comment by Izheil** [comment]
Should be fixed now on [1.8.5](https://github.com/Izheil/Quantum-Nox-Firefox-Dark-Full-Theme/releases/tag/FF108)
