### ISSUE TITLE
Multirow FF108

### ISSUE THREAD

**Issue by felitsyn** [Izheil/Dark-userstyles#6]
After upgrading to version 108 in Multirow for FF108, the active tab is hanging in the air. This is the same situation that was for Firefox Development Edition before version 1.8.5.

For a regular FF, I managed to get rid of the error by doing some manipulations with reinstalling the patch in different combinations. For the Portable version, I failed, and the error persists in Portable FF108.

**Comment by Izheil** [comment]
It looks like after Firefox Stable updated to V108 it added the selector that should have been used in developer mode, but without adding the random changes that broke developer FF.

Running version 1.8.4 should work again, either that or the latest [1.8.6](https://github.com/Izheil/Quantum-Nox-Firefox-Dark-Full-Theme/releases/tag/FF108)

**Comment by felitsyn** [comment]
Unfortunately, this did not help for the Portable version of Firefox. The tab is still up in the air. I did the same as before - inserted Root and Profile.

**Comment by Izheil** [comment]
Try to install the files [manually](https://github.com/Izheil/Quantum-Nox-Firefox-Dark-Full-Theme/tree/master/Multirow%20and%20other%20functions/JS%20Loader#installation) and see if that helps.

**Comment by Izheil** [comment]
If you were using multirow lite, that version was broken on 1.8.5-1.8.7, but it should be working now on 1.8.8.

**Comment by felitsyn** [comment]
I managed to get it to work, although not immediately. The problem turned out to be that the Multirow files are placed in the FF-Portable/Chrome folder, and not in the FF-Portable/Data/Profile/Chrome folder, as before. It is necessary to completely transfer the files from the first folder to the second. And completely delete what is in the FF-Portable / Chrome folder, otherwise they interfere.

I am using the Portable FF version with SourceForge.

Thank you.

**Comment by felitsyn** [comment]
By the way, there are two suggestions for Patcher - optional, only if it's not difficult.

1. --tab-growth is always set to 0 after Patcher is running. You have to set it to 1 every time. It is desirable that there be a setting in the Patcher that would allow you to set the value to 1, or not change this value.

2. Now I have the following order of panels: address bar - bookmarks bar - menu - tabs. Previously, the menu in FF was at the top. The menu bar is out of place - it's annoying, but I usually hide it and bring it up through Alt.
I would like to have a different order, as before: menu - address bar - bookmarks bar - tabs. (But this might be tricky, considering how many times Firefogh has changed the order of the panels at the top.)

**Comment by Izheil** [comment]
Sorry, but I'm not planning to add any new functionality to the patcher. 
The interface is already quite cluttered as it is, and I didn't really plan to add anything new to it, which is why I archived the repository.

Adding a new function would require to juggle with the tkinter code, which is kind of annoying to change.

As for 2, that's already implemented, just don't tick "menu over tabs" on the patcher, or copy the [Tabs-below.as.css](https://raw.githubusercontent.com/Izheil/Quantum-Nox-Firefox-Dark-Full-Theme/master/CSS%20tweaks/Tabs/Tabs-below.as.css) file directly to your chrome folder.

**Comment by felitsyn** [comment]
Ok, thanks.

**Comment by felitsyn** [comment]
By the way, I remembered that I had not pressed this checkmark before. But when the menu bar is hidden (and shown by pressing Alt), then instead of hiding, there is an empty line at the top. (At first I didn’t even understand that it was from the settings in Patcher.) But it’s ugly and then I got rid of this empty line.

![изображение](https://user-images.githubusercontent.com/9796044/208174904-8057ebd8-ddf9-42b1-a85c-904775c6053d.png)
