### ISSUE TITLE
Multirow 1.8.7 with FF 108 issues

### ISSUE THREAD

**Issue by Hirotaro** [Izheil/Dark-userstyles#7]
1. Multi-row Tabs + Sub-option: "All rows visible" does not work. The only way to display all rows is to select "Scrollable rows" and enter value manually (like 8-10)
2. The Minimalize, FullScreen, Close buttons limit the space for rows
3. If "Menu Bar" option is ON, there are 2 sets of Minimalize, FullScreen, Close buttons displayed
Picture attached: https://www.dropbox.com/s/r46ehumj7afx19m/issue.jpg?dl=0

For 2 & 3 the workaround is to select "Tabs below URL bar" option, but that layout is not ergonomic nor popular these days

**Comment by Izheil** [comment]
Should be fixed on version [1.8.8](https://github.com/Izheil/Quantum-Nox-Firefox-Dark-Full-Theme/releases/tag/FF108).
