### ISSUE TITLE
2.6.47 broke the Quantum nox - Global dark style theming on most webpages for me.

### ISSUE THREAD

**Issue by gripped** [Izheil/Dark-userstyles#9]
I normally use Firedragon (108.0.2)
But the behaviour is the same in Firefox (109.0.1)
Artix Linux

As soon as Stylus updates to Quantum nox - Global dark style 2.6.47 the theming breaks.
Reverting back to 2.6.46 fixes it.
I've disabled auto updates for now.

2.6.47 Pictures:
![bbc-2 6 47](https://user-images.githubusercontent.com/3513053/218151111-63f33efd-7ec7-4341-8c7a-9253352da626.png)
![dm-2 6 47](https://user-images.githubusercontent.com/3513053/218151723-09fccb09-8bae-425e-a43b-66edcf92b00b.png)

2.6.46 Pictures:
![bbc-2 6 46](https://user-images.githubusercontent.com/3513053/218151287-7a1c345f-06af-41ad-91b5-ef5e104083a6.png)
![dm-2 6 46](https://user-images.githubusercontent.com/3513053/218151302-5a48b94e-c54e-479b-900e-338231dffc47.png)

**Comment by Izheil** [comment]
Should be fixed on 2.6.48 now

**Comment by gripped** [comment]
Fix confirmed. Thanks
